name: "Release"

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 14 * * *'
  workflow_dispatch:
    inputs:
      recache:
        description: 'Delete Cache before Build?'
        required: false
        options: [ 'yes', 'no' ]
        type: choice
        default: 'no'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  COMPARE_FILE0: /tmp/.compare-content-0.txt
  COMPARE_FILE1: /tmp/.compare-content-1.txt
  SEVENZ_VERSION: 26.02

jobs:
  clear_cache:
    runs-on: ubuntu-slim
    if: ${{ github.event.inputs.recache == 'yes' }}
    permissions:
      actions: write
      contents: read

    steps:
      - name: clear_cache
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ONWER: ${{ github.repository_owner }}
          GH_REPO: ${{ github.event.repository.name }}
        shell: bash
        run: |
          set -e +o pipefail
          echo "::notice::Recache selected - Deleting all caches for this workflow ..."
          gh cache delete --all --succeed-on-no-caches \
            --repo $GH_ONWER/$GH_REPO

  generate:
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: x64
            runner: ubuntu-26.04
          - arch: arm64
            runner: ubuntu-26.04-arm
    runs-on: ${{ matrix.runner }}
    if: ${{ !cancelled() && needs.clear_cache.result != 'failure' }}
    needs: [ clear_cache ]
    outputs:
      SEVENZ_CHECK_VERSION: ${{ steps.check.outputs.SEVENZ_CHECK_VERSION }}
      latest_version: ${{ steps.compare.outputs.latest_version }}
      key: ${{ steps.env.outputs.key }}
      compare-env: ${{ steps.upload-compare.outputs.compare-env }}
    steps:
      - name: env
        id: env
        run: |
          export KEY="${{ github.job }}"
          echo "key=$KEY" >> $GITHUB_OUTPUT
          echo "################################################################" && bash -c "echo KEY=$KEY"

          export ARCH="${{ matrix.arch }}"
          echo "arch=$ARCH" >> $GITHUB_OUTPUT
          echo "################################################################" && bash -c "echo ARCH=$ARCH"

          echo "keymatrix=$KEY-$ARCH" >> $GITHUB_OUTPUT

      - name: locale
        run: sudo $SHELL -c "locale-gen en_US.utf8 && update-locale"

      - name: clone
        uses: actions/checkout@v7
        with:
          clean: false

      - name: cache_7zbin
        uses: actions/cache@v6
        with:
          path: |
            /tmp/7z-linux-${{ matrix.arch }}.tar.xz
          key: ${{ steps.env.outputs.keymatrix }}-7z-${{ env.SEVENZ_VERSION }}

      - name: dependencies
        run: |
          SEVENZ_VERSION_NO_DOT=$(printf '%s' "$SEVENZ_VERSION" | tr -d '.')
          [ ! -f /tmp/7z-linux-${{ matrix.arch }}.tar.xz ] && wget -q -O /tmp/7z-linux-${{ matrix.arch }}.tar.xz "https://github.com/ip7z/7zip/releases/download/${SEVENZ_VERSION}/7z${SEVENZ_VERSION_NO_DOT}-linux-${{ matrix.arch }}.tar.xz"
          sudo tar -xf /tmp/7z-linux-${{ matrix.arch }}.tar.xz -C /usr/local/bin/ 7zzs
          sudo ln -sf /usr/local/bin/7zzs /usr/local/bin/7z
          sudo chmod +x /usr/local/bin/7zzs /usr/local/bin/7z
        
      - name: download
        run: |
          rm -rf App/LMStudio && mkdir -p App/LMStudio
          wget -q -O LMStudioInstaller.exe https://lmstudio.ai/download/latest/win32/${{ matrix.arch }}
      
      - name: check
        id: check
        run: |
          7z t LMStudioInstaller.exe >/tmp/7z_check.log
          SEVENZ_CHECK_VERSION="$(grep "ProductVersion" /tmp/7z_check.log | head -n1 | awk -F' ' '{ print $2 }' 2>/dev/null)"
          [ -z "$SEVENZ_CHECK_VERSION" ] && echo "7z_check_version: not found" && exit 1
          [ -n "$SEVENZ_CHECK_VERSION" ] && echo "7z_check_version: $SEVENZ_CHECK_VERSION"
          echo "SEVENZ_CHECK_VERSION=$SEVENZ_CHECK_VERSION" >> $GITHUB_OUTPUT

      - name: cache_load
        uses: actions/cache/restore@v6
        with:
          path: |
            ${{ env.COMPARE_FILE0 }}
          key: ${{ steps.env.outputs.key }}-${{ github.run_id }}
          restore-keys: |
            ${{ steps.env.outputs.key }}-

      - name: compare
        shell: bash
        id: compare
        run: |
          echo "${{ steps.check.outputs.SEVENZ_CHECK_VERSION }}" > ${{ env.COMPARE_FILE1 }}

          if [ ! -e "${{ env.COMPARE_FILE0 }}" ]; then
            echo "copy File for cache"
            cp ${{ env.COMPARE_FILE1 }} ${{ env.COMPARE_FILE0 }}
          else
            CONTENT_FILE0=$(cat ${{ env.COMPARE_FILE0 }})
            CONTENT_FILE1=$(cat ${{ env.COMPARE_FILE1 }})
            if [ "$CONTENT_FILE0" = "$CONTENT_FILE1" ]; then
              echo "Still at latest version"
              echo "latest_version=true" >> $GITHUB_OUTPUT
            else
              echo "Not at latest version"
              cp ${{ env.COMPARE_FILE1 }} ${{ env.COMPARE_FILE0 }}
            fi
          fi

      - name: generate
        if: steps.compare.outputs.latest_version != 'true'
        env:
          LANG: en_US.utf8
        run: |
          #prepare
          ARCH_WITHOUT_X=$(printf '%s' "${{ matrix.arch }}" | tr -d 'x')
          
          #extract
          7z x LMStudioInstaller.exe "\$PLUGINSDIR/app-${ARCH_WITHOUT_X}.7z" -o./ && rm -f LMStudioInstaller.exe
          7z x "\$PLUGINSDIR/app-${ARCH_WITHOUT_X}.7z" -o./App/LMStudio && rm -rf "\$PLUGINSDIR/app-${ARCH_WITHOUT_X}.7z"

          #repack
          7z a -t7z -mx=3 -mmt=on -m0=lzma2 /tmp/LMStudioPortable-${{ matrix.arch }}.7z \
            ./App \
            ./Other \
            ./help.html \
            ./LICENSE.txt \
            LMStudioPortable.exe

      - name: upload
        if: steps.compare.outputs.latest_version != 'true'
        uses: actions/upload-artifact@v7
        with:
          name: LMStudioPortable-${{ matrix.arch }}.7z
          path: /tmp/LMStudioPortable-${{ matrix.arch }}.7z
          archive: false
      - name: upload-compare
        id: upload-compare
        if: steps.compare.outputs.latest_version != 'true'
        run: echo "compare-env=$(cat ${{ env.COMPARE_FILE0 }})" >> $GITHUB_OUTPUT

  release:
    needs: [ generate ]
    runs-on: ubuntu-slim
    if: ${{ !cancelled() && needs.generate.result == 'success' && needs.generate.outputs.latest_version != 'true' }}
    permissions:
      contents: write
    steps:
      - name: download
        if: needs.generate.outputs.latest_version != 'true'
        uses: actions/download-artifact@v8
        with:
          path: /tmp
          pattern: LMStudioPortable-*.7z
          merge-multiple: true
      - name: download-compare
        id: download-compare
        if: needs.generate.outputs.latest_version != 'true'
        run: echo "${{ needs.generate.outputs.compare-env }}" > ${{ env.COMPARE_FILE0 }}

      - name: Delete existing tag
        shell: sh
        env:
          GH_TOKEN: ${{ github.token }}
          GH_OWNER_REPO: ${{ github.repository }}
        continue-on-error: true
        if: needs.generate.outputs.latest_version != 'true'
        run: gh release delete "${{ needs.generate.outputs.SEVENZ_CHECK_VERSION }}" --cleanup-tag --yes --repo $GH_OWNER_REPO

      - name: Publish release files
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          GH_OWNER_REPO: ${{ github.repository }}
          TAG_NAME: ${{ needs.generate.outputs.SEVENZ_CHECK_VERSION }}
        if: needs.generate.outputs.latest_version != 'true'
        run: |
          # create release-notes
          cat > /tmp/release-notes.txt <<EOF
          ### LMStudio Portable
          - Version: ${TAG_NAME}
          EOF
          # create release
          gh release create "${TAG_NAME}" \
            --title "LMStudio Portable ${TAG_NAME}" \
            --notes-file /tmp/release-notes.txt \
            --prerelease=false \
            --draft=false \
            --latest=true \
            --repo "$GH_OWNER_REPO" \
            $(find /tmp/LMStudioPortable-*.7z -type f)

      - name: cache_save
        if: needs.generate.outputs.latest_version != 'true'
        uses: actions/cache/save@v6
        with:
          path: |
            ${{ env.COMPARE_FILE0 }}
          key: ${{ needs.generate.outputs.key }}-${{ github.run_id }}
